services:
  dashboard:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: botchat-dashboard
    ports:
      - "3000:3000"
    env_file:
      - ./front/.env
    depends_on:
      - bot
    restart: unless-stopped

  bot:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: botchat-api
    ports:
      - "3002:3002"
    env_file:
      - ./api/.env
    restart: unless-stopped
    volumes:
      - ./api/src/bots/baileys/sessions:/app/src/bots/baileys/sessions
      - ./api/src/bots/baileys/audios:/app/src/bots/baileys/audios
