// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { databaseEnv } from "./src/env";

const push = true

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: push ? databaseEnv.DIRECT_URL : databaseEnv.DATABASE_URL,
    shadowDatabaseUrl: push ? databaseEnv.DATABASE_URL : databaseEnv.DIRECT_URL,
  },
});
